export type Locale = "es" | "en";

export const copy = {
  es: {
    app: "FreeSubtiless",
    tagline: "Lo que se dijo, en el idioma que elijas.",
    blurb:
      "Suelta un video. Transcribimos la voz tal cual — groserías, muletillas y tono — y la traducimos sin recortar ni suavizar.",
    source: "Idioma del audio",
    target: "Subtítulos en",
    targetHint: "Los subtítulos salen en esta lengua, fieles al audio. Nada se tapa.",
    dropTitle: "Suelta el video aquí",
    dropHint: "MP4, WebM o MOV. Hasta 12 minutos.",
    browse: "Elegir archivo",
    demo: "Ver un ejemplo",
    processing: "Procesando",
    extract: "Leyendo el audio",
    transcribe: "Transcribiendo la voz",
    translate: "Traduciendo subtítulos",
    ready: "Listo",
    cancel: "Cancelar",
    generate: "Generar subtítulos",
    generating: "Generando…",
    newVideo: "Otro video",
    exportVideo: "Descargar video",
    exportSrt: "SRT",
    srtHelp: "Archivo de subtítulos para VLC, el celular o la PC. El video y los textos van por separado.",
    exportVtt: "VTT",
    exporting: "Exportando…",
    converting: "Pasando a MP4…",
    exportError: "No se pudo armar el video. Prueba de nuevo o descarga el SRT.",
    format: "Formato",
    savedMp4: "Video MP4 descargado",
    savedWebm: "Video WebM descargado",
    savedWebmFallback: "No se pudo pasar a MP4. Te dejé WebM; ábrelo en VLC.",
    install: "Instalar app",
    installTitle: "Úsala como app, no como instalador",
    installBlurb:
      "FreeSubtiless vive en el navegador. Descargar video te da el clip subtitulado, no un .exe ni un .apk. Para tenerla en el celular o la PC, instálala aquí: queda el icono y se abre como cualquier app.",
    installIos: "En iPhone: toca Compartir y luego Añadir a pantalla de inicio.",
    installDesktop: "En Chrome o Edge de la computadora: Instalar, o el icono ⊕ junto a la dirección.",
    installDone: "Ya está instalada en este dispositivo.",
    style: "Estilo",
    texts: "Textos",
    type: "Tipografía",
    color: "Color",
    shadow: "Sombra",
    box: "Caja",
    position: "Posición",
    presets: "Presets",
    font: "Fuente",
    size: "Tamaño",
    weight: "Peso",
    tracking: "Tracking",
    leading: "Interlineado",
    uppercase: "Mayúsculas",
    fill: "Relleno",
    outline: "Contorno",
    outlineW: "Grosor",
    blur: "Desenfoque",
    offsetX: "Despl. X",
    offsetY: "Despl. Y",
    opacity: "Opacidad",
    enabled: "Activar",
    padding: "Relleno",
    radius: "Radio",
    align: "Alineación",
    maxWidth: "Ancho máx.",
    yOffset: "Altura",
    top: "Arriba",
    center: "Centro",
    bottom: "Abajo",
    left: "Izq.",
    right: "Der.",
    addCue: "Añadir línea",
    emptyCues: "Aún no hay subtítulos. Genera a partir del audio o escribe una línea.",
    noSpeech: "No se detectó voz en el video. Puedes escribir los textos a mano.",
    aiOff: "La transcripción automática no está disponible ahora. Puedes subtitular a mano.",
    done: "Subtítulos listos",
    translatedFrom: "Traducido de {from} a {to}.",
    translateFail: "Se transcribió el audio, pero no se pudo traducir. Pulsa Generar otra vez.",
    share: "Compartir",
    detected: "Audio detectado",
    errorGeneric: "No se pudo procesar el video.",
    errorAudio: "No se pudo leer el audio. Prueba con un MP4 o WebM.",
    errorTooLong: "El video supera los 12 minutos.",
    savedVideo: "Video descargado",
    savedSrt: "Archivo SRT descargado",
    savedVtt: "Archivo VTT descargado",
    play: "Reproducir",
    pause: "Pausar",
    original: "Original",
    restore: "Dejar el original",
    uiEs: "ES",
    uiEn: "EN",
    footer: "Transcribimos lo dicho, sin recortar. El montaje queda en tu navegador.",
  },
  en: {
    app: "FreeSubtiless",
    tagline: "What was said, in the language you pick.",
    blurb:
      "Drop a video. We transcribe the voice as spoken — swearing, fillers, tone — and translate it without cutting or softening.",
    source: "Audio language",
    target: "Captions in",
    targetHint: "Captions land in this language, faithful to the audio. Nothing is covered up.",
    dropTitle: "Drop the video here",
    dropHint: "MP4, WebM or MOV. Up to 12 minutes.",
    browse: "Choose file",
    demo: "Try a sample",
    processing: "Processing",
    extract: "Reading audio",
    transcribe: "Transcribing speech",
    translate: "Translating captions",
    ready: "Ready",
    cancel: "Cancel",
    generate: "Generate captions",
    generating: "Generating…",
    newVideo: "New video",
    exportVideo: "Download video",
    exportSrt: "SRT",
    srtHelp: "Subtitle file for VLC, phones, or computers. Video and text stay separate.",
    exportVtt: "VTT",
    exporting: "Exporting…",
    converting: "Encoding MP4…",
    exportError: "Could not build the video. Try again, or download the SRT.",
    format: "Format",
    savedMp4: "MP4 video downloaded",
    savedWebm: "WebM video downloaded",
    savedWebmFallback: "Could not make MP4. You got WebM — open it in VLC.",
    install: "Install app",
    installTitle: "Use it as an app, not an installer",
    installBlurb:
      "FreeSubtiless lives in the browser. Download video gives you the captioned clip, not an .exe or .apk. To keep it on your phone or computer, install it here: you get an icon and it opens like any app.",
    installIos: "On iPhone: tap Share, then Add to Home Screen.",
    installDesktop: "On Chrome or Edge on a computer: Install, or the ⊕ icon by the address bar.",
    installDone: "Already installed on this device.",
    style: "Style",
    texts: "Lines",
    type: "Type",
    color: "Color",
    shadow: "Shadow",
    box: "Box",
    position: "Position",
    presets: "Presets",
    font: "Font",
    size: "Size",
    weight: "Weight",
    tracking: "Tracking",
    leading: "Leading",
    uppercase: "Uppercase",
    fill: "Fill",
    outline: "Outline",
    outlineW: "Weight",
    blur: "Blur",
    offsetX: "Offset X",
    offsetY: "Offset Y",
    opacity: "Opacity",
    enabled: "Enable",
    padding: "Padding",
    radius: "Radius",
    align: "Align",
    maxWidth: "Max width",
    yOffset: "Height",
    top: "Top",
    center: "Center",
    bottom: "Bottom",
    left: "Left",
    right: "Right",
    addCue: "Add line",
    emptyCues: "No captions yet. Generate from audio or write a line.",
    noSpeech: "No speech was found. You can type the lines yourself.",
    aiOff: "Automatic transcription is unavailable. You can caption by hand.",
    done: "Captions ready",
    translatedFrom: "Translated from {from} to {to}.",
    translateFail: "The audio was transcribed, but translation failed. Tap Generate again.",
    share: "Share",
    detected: "Audio detected",
    errorGeneric: "Could not process the video.",
    errorAudio: "Could not read the audio. Try an MP4 or WebM file.",
    errorTooLong: "The video is longer than 12 minutes.",
    savedVideo: "Video downloaded",
    savedSrt: "SRT file downloaded",
    savedVtt: "VTT file downloaded",
    play: "Play",
    pause: "Pause",
    original: "Original",
    restore: "Use original",
    uiEs: "ES",
    uiEn: "EN",
    footer: "We transcribe what was said, uncut. The picture stays in your browser.",
  },
} as const;

export type Copy = (typeof copy)[Locale];

export const DEMO_CUES: Record<
  Locale,
  { start: number; end: number; text: string }[]
> = {
  es: [
    { start: 0.4, end: 3.3, text: "La luz se queda en los cristales." },
    { start: 3.6, end: 6.7, text: "El campo pasa, y no vuelve." },
    { start: 7.0, end: 9.8, text: "Seguimos. Como si el día no se acabara." },
  ],
  en: [
    { start: 0.4, end: 3.3, text: "Light stays on the glass." },
    { start: 3.6, end: 6.7, text: "The fields go by, and don't come back." },
    { start: 7.0, end: 9.8, text: "We keep going. As if the day would never end." },
  ],
};
